[build]
  command = "ng build"
  publish = "dist/webseite/browser"

[functions]
  [functions.server]
    main_file = "dist/webseite/server/server.mjs"
    node_bundler = "esbuild"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200