name: 🐞 Bug
description: Fehler oder Problem melden
title: 'Fix: '
labels: ['bug']
body:
  - type: input
    id: title
    attributes:
      label: Titel des Fehlers
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
