name: 🐞 Bug
description: Fehler oder Problem melden
labels: ['bug']
body:
  - type: input
    id: title
    attributes:
      label: Titel des Fehlers
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung

  - type: markdown
    attributes:
      value: |
        **Hinweis:** Dieses Issue wird automatisch als `Fix[WSFC-XXX]` nummeriert.

  - type: input
    id: prefix
    attributes:
      label: Prefix
      default: 'Fix'
    validations:
      required: true
