name: 🛠️ Chore
description: Interne Aufgabe, Maintenance oder Setup
title: 'Chore: '
labels: ['chore']
body:
  - type: input
    id: title
    attributes:
      label: Titel der Aufgabe
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
