name: 🛠️ Chore
description: Interne Aufgabe oder Wartung
labels: ['chore']
body:
  - type: input
    id: title
    attributes:
      label: Titel der Aufgabe
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung

  - type: markdown
    attributes:
      value: |
        **Hinweis:** Diese Aufgabe wird automatisch als `Chore[WSFC-XXX]` nummeriert.

  - type: input
    id: prefix
    attributes:
      label: Prefix
      default: 'Chore'
    validations:
      required: true
