name: 🚀 Feature
description: Neue Funktion oder Erweiterung
labels: ['enhancement']
body:
  - type: input
    id: title
    attributes:
      label: Titel des Features
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung

  - type: markdown
    attributes:
      value: |
        **Hinweis:** Dieses Feature wird automatisch als `Feat[WSFC-XXX]` nummeriert.

  - type: input
    id: prefix
    attributes:
      label: Prefix
      default: 'Feat'
    validations:
      required: true
