version: '3.9'

services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: webseite_frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.webseite.rule=Host(`development.simonfischer.dev`)'
      - 'traefik.http.routers.tinyshop.entrypoints=websecure'
      - 'traefik.http.routers.tinyshop.tls.certresolver=basic'
      - 'traefik.http.services.webseite.loadbalancer.server.port=80'
    networks:
      - traefik

networks:
  traefik:
    external: true
