name: Auto WSFC Numbering (YAML Templates)

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-number:
    runs-on: ubuntu-latest
    steps:
      - name: Add WSFC Number to Issue Title
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;

            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            const originalTitle = issue.title;

            const labels = issue.labels.map(l => l.name.toLowerCase());
            let prefix = "Task";
            if (labels.includes("bug")) prefix = "Fix";
            else if (labels.includes("enhancement")) prefix = "Feat";
            else if (labels.includes("chore")) prefix = "Chore";

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });

            const numbers = issues
              .map(i => {
                const match = i.title.match(/WSFC-(\d{3})/);
                return match ? parseInt(match[1], 10) : null;
              })
              .filter(n => n !== null)
              .sort((a, b) => b - a);

            const nextNumber = numbers.length > 0 ? numbers[0] + 1 : 1;
            const paddedNumber = String(nextNumber).padStart(3, '0');

            const newTitle = `${prefix}[WSFC-${paddedNumber}]: ${originalTitle}`;

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              title: newTitle
            });
